# Generated by Django 5.2.7 on 2025-11-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_evaluation_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
