# Generated by Django 5.2.7 on 2025-12-04 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_scans', models.JSONField(default=list)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('document_snapshot', models.TextField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_evaluations', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.module')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('Academic Metadata Scan', 'Academic Metadata Scan'), ('Learning Content Scan', 'Learning Content Scan'), ('Assessment Scan', 'Assessment Scan'), ('Multimedia Scan', 'Multimedia Scan'), ('Certificate Scan', 'Certificate Scan'), ('Summary Scan', 'Summary Scan')], max_length=100)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='In Progress', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='evaluations.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
