# Generated by Django 5.2.7 on 2026-04-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.module'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.rubric'),
        ),
        migrations.AddField(
            model_name='scan',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='usermodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='evaluations.module'),
        ),
        migrations.AddField(
            model_name='usermodule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['module', '-created_at'], name='evaluations_module__6c61fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=models.UniqueConstraint(fields=('evaluation', 'scan_type'), name='unique_scan_per_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='usermodule',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module'),
        ),
    ]
