# Generated by Django 5.2.7 on 2026-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_criterion_user_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='user_selection',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT APPLICABLE', 'Not Applicable')], max_length=50, null=True),
        ),
    ]
