# Generated by Django 5.2.7 on 2026-06-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_scan_updated_at_metadata_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='rubric_map',
        ),
    ]
