services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 2. The Redis Broker for Celery
  broker:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 3. The Django App
  app:
    build: .
    ports:
      - "127.0.0.1:8004:8000"
    volumes:
      - .:/app
      - ${STATIC_VOLUME_PATH}:/app/staticfiles
    env_file: .env
    depends_on:
      - db
      - broker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 4. The Celery Worker
  celery_worker:
    build: .
    command: celery -A evaluator_api worker -l info
    env_file: .env
    depends_on:
      - db
      - broker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  redis_data:
