services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: ${RESTART_POLICY}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 2. The Redis Broker for Celery
  broker:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 3. The Django App
  app:
    build: .
    ports:
      - "127.0.0.1:8004:8000"
    volumes:
      - ${STATIC_VOLUME_PATH}:/app/staticfiles
      - logs_data:/app/logs
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 4. The Celery Worker
  celery_worker:
    build: .
    command: celery -A evaluator_api worker -l info -n worker1@%h --concurrency=4
    volumes:
      - logs_data:/app/logs
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  # 5. The Celery Beat Scheduler
  celery_beat:
    build: .
    command: celery -A evaluator_api beat -l info --pidfile=
    volumes:
      - logs_data:/app/logs
    env_file: .env
    restart: ${RESTART_POLICY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
      celery_worker:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  logs_data:
