# Generated by Django 5.2.7 on 2026-02-23 21:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0006_alter_evaluation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_reviews', to='evaluations.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'reviewer_email')},
            },
        ),
        migrations.CreateModel(
            name='CriterionFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_feedbacks', to='evaluations.criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='reviews.externalreview')),
            ],
            options={
                'unique_together': {('review', 'criterion')},
            },
        ),
    ]
