# Generated by Django 5.2.7 on 2026-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreview',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
