# Generated by Django 5.2.7 on 2026-03-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reviewer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('AI Review', 'AI Review'), ('Peer Review', 'Peer Review')], default='AI Review', max_length=50),
        ),
    ]
