version: '3.8'

services:
  # 1. The Redis Broker for Celery
  broker:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # 2. The Django App (running Gunicorn)
  app:
    build: .
    ports:
      - "127.0.0.1:8005:8000"
    volumes:
      - ./staticfiles:/app/static
      - sqlite_db:/app/db
    env_file: .env.prod
    environment:
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      - broker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # 4. The Celery Worker
  celery_worker:
    build: .
    command: celery -A app worker --loglevel=info -P solo
    volumes:
      - sqlite_db:/app/db
    env_file: .env.prod
    environment:
      - TOKENIZERS_PARALLELISM=false
      - PYTHONUNBUFFERED=1
    depends_on:
      - broker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  sqlite_db:
  redis_data:
  